name: Swift CI/CD

on:
  push:
    branches:
      - desired-branch-name

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Test
      run: |
        xcodebuild clean test -project ./bubbel/bubbel.xcodeproj -scheme bubbel -destination "platform=iOS Simulator,name=iPhone 14 Pro Max" CODE_SIGNING_REQUIRED=NO
