# This workflow will build an Xcode project

name: Xcode Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        run: xcodebuild -project bubbel.xcodeproj -scheme bubbel build
