name: Swift CI/CD

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: macos-latest  # macOS is needed for Swift development

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2


    - name: Build and Test
      run: |
        xcodebuild clean test -project bubbel.xcodeproj -scheme bubbel -destination "platform=iOS Simulator,name=iPhone 14" CODE_SIGNING_REQUIRED=NO
